name: student_database_using_provider
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  photo_view: ^0.14.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1


flutter:

 
  uses-material-design: true
 
  assets:
  - assets/registration_background.png
  - assets/register_bg.png
  - assets/avatar.jpg
 
